#!/bin/bash
##########################################################
#                                                        #
# check_vault                                            #
#                                                        #
# Author: Christophe Vanlancker <carroarmato0@inuits.eu> #
#                                                        #
# This is a simple Nagios/Icinga check which will query  #
# the state of Vault.                                    #
#                                                        #
# 2017-10-10:                                            #
#  - Initial release                                     #
#                                                        #
##########################################################

OK=0;
WARNING=1;
CRITICAL=2;
UNKNOWN=3;

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin

OUTPUT="$(bash -c 'vault status 2>&1')";

if [[ $OUTPUT == *"command not found"* ]]; then
  echo "Vault command not found";
  exit $UNKNOWN;
elif [[ $OUTPUT == *"connection refused"* ]]; then
  echo "Unable to connect to server";
  exit $CRITICAL;
elif [[ $OUTPUT == *"server is not yet initialized"* ]]; then
  echo "Vault not initialized";
  exit $WARNING;
elif [[ $OUTPUT == *"Sealed: true"* ]]; then
  KEY_THRESHOLD="$(echo $OUTPUT | egrep -o 'Key Threshold: [[:digit:]]' | cut -d ':' -f2 | sed 's/^[ \t]*//;s/[ \t]*$//')";
  USEAL_PROGRESS="$(echo $OUTPUT | egrep -o 'Unseal Progress: [[:digit:]]' | cut -d ':' -f2 | sed 's/^[ \t]*//;s/[ \t]*$//')";
  echo "Vault sealed, $USEAL_PROGRESS/$KEY_THRESHOLD entered";
  exit $WARNING;
elif [[ $OUTPUT == *"Sealed: false"* ]]; then
  echo "Vault unsealed";
  exit $OK;
else
  echo "Vault in an unknown state.\n";
  echo $OUTPUT;
  exit $UNKNOWN;
fi

